name: Teams Manager
on:
  push:
    paths:
      - ".github/workflows/teams-manager.yml"
      - "teams.yaml"
  workflow_dispatch:

jobs:
  update-teams:
    if: github.ref_name == 'master' && github.repository == 'running-linux-riscv/.github'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update teams
        uses: linuxdeepin/action-teams-manager@master
        with:
          app_id: 312940
          installationId: 35978164
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          config_file: teams.yaml

      - name: generate teams.yaml
        uses: linuxdeepin/action-teams-manager@master
        with:
          app_id: 312940
          installationId: 35978164
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          config_file: teams.yaml
          generate_yaml: true
          update_teams: false
